### ISSUE TITLE
Braki

### ISSUE THREAD

**Issue by Kitee666** [ChameleonLinux/subnautica.cos.ovh#3]
<div> etc.
Coversy - patrz Aurora.
== xxx == -  nie wiem do cholery co to było, ale jest w nagłówkach.
Wypunktowanie - brak możliwości zrobienia podpunktu.
Hiperłącze do obrazka.
Dodanie możliwości dodania dźwięków.
Dodanie refferencji.

**Comment by Py64** [comment]
Kitlov, coś ty ćpał? Mów logicznie!

**Comment by Py64** [comment]
Referencje? tzn. przypisy?
test[ ^1]

[ ^1]: test!

**Comment by Py64** [comment]
Punkty?
(myślnik) punkt
(myślnik) (myślnik) podpunkt

**Comment by Py64** [comment]
Hiperłącza, klucz link.

**Comment by Py64** [comment]
Audio? {% audio plik: "aaa.ogg" %}

**Comment by Kitee666** [comment]
Chmm wiesz może jak dodać linki do kategorii? (nie metadane)
[coś](/Kategorie/Kategoria) ?

**Comment by Py64** [comment]
tak

**Comment by Py64** [comment]
Nawet więcej - (coś)[/kategoria/Kategoria]
